author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/getEncryption'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 3
      #school 学校全称
      schoolName: 永州职业技术学院
      #username 学号或者工号
      username: ''
      #password 密码
      password: ''
      # 地址信息
      address: '永州市冷水滩区'
      # sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 111.631109
      #lat 纬度
      lat: 26.221936
      # 检查标题与否
      checkTitle: 1
      # 代理ip信息（若无可忽略本设置、该配置仅供您所在环境ip被ban且自己拥有代理ip使用）（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy: ''
      # isOffset 坐标偏移开关，默认打开坐标偏移开关，若一直出现不在签到范围且确保自己填写的lon和lat在坐标范围内，请尝试关闭本功能
      isOffset: true
      # 表单信息
      #forms:
       # - form:
           # title: 2.是否在校上班或居住
            #value: 是
        
  # 第三个用户配置
  # 以下配置为签到
  # 这里默认仅适配武汉船舶职业技术学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '202013060290'
      #password 密码
      password: '0121twj@yhn'
      #address 地址，定位信息
      address: '湖南省永州市零陵区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '1794502705@qq.com'
      #school 学校全称
      schoolName: 永州职业技术学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 111.597568
      #lat 纬度
      lat: 26.46237
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      # 代理ip信息（若无可忽略本设置、该配置仅供您所在环境ip被ban且自己拥有代理ip使用）（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy: ''
      # isOffset 坐标偏移开关，默认打开坐标偏移开关，若一直出现不在签到范围且确保自己填写的lon和lat在坐标范围内，请尝试关闭本功能
      isOffset: true
      # 表单信息
      forms:
        - form:
            title: 当前位置不在范围之内
            value: 继续签到
        #- form:
            #title: 今天你的身体状况是？
          #  value: 健康
  # 第四个用户配置
  # 以下配置为查寝
  # 这里默认仅适配四川信息职业技术学院，其他学校自行修改
  
